sequenceDiagram
    actor User
    participant Cortext
    box Encoding
       participant VE as Vision Encoder
       participant AE as Audio Encoder
    end
    participant Processor
    participant AO as Affect Operation
    participant MC as Memory Controller

    User->>Cortext: Process(input_signal)
    activate Cortext
    alt audio?
      Cortext->>AE: Encode(input_signal)
      AE-->>Cortext: encoded_signal
    else visual?
      Cortext->>VE: Encode(input_signal)
      VE-->>Cortext: encoded_signal
    end
    Cortext->>Processor: Process(encoded_signal)
    activate Processor
   
    Processor->>AO: Execute(encoded_signal)
    activate AO
    AO-->>Processor: encoded_signal_with_affect
    deactivate AO
    Processor->>MC: UpdateAndRetrieve(encoded_signal_with_affect)
    activate MC
    MC-->>Processor: memories
    deactivate MC
    Processor-->>Cortext: memories
    Cortext-->>User: context
    deactivate Cortext

